### ISSUE TITLE
Create python microservice to compute consensus

### ISSUE THREAD

**Issue by slaterb1** [UVProtocol/data#1]
# Overview

Computations for the UVProtocol MVP will be handled in python, so a microservice needs to be setup. Initially it will only compute the consensus, reward calculations will be added in a future milestone.

# Expected Behavior

The consensus service in UVProtocol/api will POST data to this microservice, the microservice will compute the consensus, then send the results back to UVProtocol/api.

# Current Behavior

Microservice has not yet been setup.

# Tasks

- [ ] create python microservice
- [ ] implement consensus algorithms
- [ ] receive proper response to request in UVProtocol/api
- [ ] add outlier detection to consensus algorithms
- [ ] write automated tests to evaluate robustness of calculations
